"""Seed authentic All-India Partner Institutions and Facilitation Centers."""
import uuid
import os
import sys

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# Ensure backend root is on sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.core.database import SessionLocal
from app.models import Institution


INSTITUTIONS_SEED_DATA = [
    {
        "name": "Indian Institute of Technology Madras",
        "short_name": "IIT Madras",
        "code": "U-0456",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "city": "Chennai",
        "address": "IIT P.O., Chennai, Tamil Nadu 600036",
        "website": "https://www.iitm.ac.in",
        "nirf_rank": 1,
        "latitude": 12.9915,
        "longitude": 80.2337,
    },
    {
        "name": "Indian Institute of Technology Delhi",
        "short_name": "IIT Delhi",
        "code": "U-0092",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Delhi",
        "district": "South Delhi",
        "city": "New Delhi",
        "address": "Hauz Khas, New Delhi 110016",
        "website": "https://home.iitd.ac.in",
        "nirf_rank": 2,
        "latitude": 28.5450,
        "longitude": 77.1926,
    },
    {
        "name": "Indian Institute of Technology Bombay",
        "short_name": "IIT Bombay",
        "code": "U-0306",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Maharashtra",
        "district": "Mumbai Suburban",
        "city": "Mumbai",
        "address": "Main Gate Rd, IIT Area, Powai, Mumbai 400076",
        "website": "https://www.iitb.ac.in",
        "nirf_rank": 3,
        "latitude": 19.1334,
        "longitude": 72.9133,
    },
    {
        "name": "Indian Institute of Technology Kanpur",
        "short_name": "IIT Kanpur",
        "code": "U-0500",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Uttar Pradesh",
        "district": "Kanpur Nagar",
        "city": "Kanpur",
        "address": "Kalyanpur, Kanpur, Uttar Pradesh 208016",
        "website": "https://www.iitk.ac.in",
        "nirf_rank": 4,
        "latitude": 26.5123,
        "longitude": 80.2329,
    },
    {
        "name": "Indian Institute of Technology Roorkee",
        "short_name": "IIT Roorkee",
        "code": "U-0560",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Uttarakhand",
        "district": "Haridwar",
        "city": "Roorkee",
        "address": "Roorkee, Haridwar District, Uttarakhand 247667",
        "website": "https://www.iitr.ac.in",
        "nirf_rank": 5,
        "latitude": 29.8649,
        "longitude": 77.8966,
    },
    {
        "name": "Indian Institute of Technology Kharagpur",
        "short_name": "IIT Kharagpur",
        "code": "U-0570",
        "institution_type": "IIT / Institute of National Importance",
        "state": "West Bengal",
        "district": "Paschim Medinipur",
        "city": "Kharagpur",
        "address": "Kharagpur, West Bengal 721302",
        "website": "https://www.iitkgp.ac.in",
        "nirf_rank": 6,
        "latitude": 22.3149,
        "longitude": 87.3105,
    },
    {
        "name": "Indian Institute of Technology Guwahati",
        "short_name": "IIT Guwahati",
        "code": "U-0053",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Assam",
        "district": "Guwahati (Kamrup Metro)",
        "city": "Guwahati",
        "address": "Amingaon, North Guwahati, Assam 781039",
        "website": "https://www.iitg.ac.in",
        "nirf_rank": 7,
        "latitude": 26.1878,
        "longitude": 91.6916,
    },
    {
        "name": "Indian Institute of Technology Hyderabad",
        "short_name": "IIT Hyderabad",
        "code": "U-0013",
        "institution_type": "IIT / Institute of National Importance",
        "state": "Telangana",
        "district": "Sangareddy",
        "city": "Kandi",
        "address": "Near NH-65, Sangareddy, Kandi, Telangana 502285",
        "website": "https://www.iith.ac.in",
        "nirf_rank": 8,
        "latitude": 17.5947,
        "longitude": 78.1230,
    },
    {
        "name": "National Institute of Technology Tiruchirappalli",
        "short_name": "NIT Trichy",
        "code": "U-0467",
        "institution_type": "NIT / Institute of National Importance",
        "state": "Tamil Nadu",
        "district": "Tiruchirappalli",
        "city": "Tiruchirappalli",
        "address": "Tanjore Main Road, National Highway 67, Tiruchirappalli, Tamil Nadu 620015",
        "website": "https://www.nitt.edu",
        "nirf_rank": 9,
        "latitude": 10.7589,
        "longitude": 78.8132,
    },
    {
        "name": "National Institute of Technology Karnataka",
        "short_name": "NIT Surathkal",
        "code": "U-0237",
        "institution_type": "NIT / Institute of National Importance",
        "state": "Karnataka",
        "district": "Dakshina Kannada (Mangaluru)",
        "city": "Mangaluru",
        "address": "NH 66, Srinivasnagar, Surathkal, Mangaluru, Karnataka 575025",
        "website": "https://www.nitk.ac.in",
        "nirf_rank": 12,
        "latitude": 13.0110,
        "longitude": 74.7943,
    },
    {
        "name": "National Institute of Technology Warangal",
        "short_name": "NIT Warangal",
        "code": "U-0025",
        "institution_type": "NIT / Institute of National Importance",
        "state": "Telangana",
        "district": "Warangal",
        "city": "Warangal",
        "address": "Kazipet, Hanamkonda, Warangal, Telangana 506004",
        "website": "https://www.nitw.ac.in",
        "nirf_rank": 21,
        "latitude": 17.9836,
        "longitude": 79.5308,
    },
    {
        "name": "Birla Institute of Technology and Science, Pilani",
        "short_name": "BITS Pilani",
        "code": "U-0391",
        "institution_type": "Deemed to be University / Institute of Eminence",
        "state": "Rajasthan",
        "district": "Jhunjhunu",
        "city": "Pilani",
        "address": "Vidya Vihar, Pilani, Rajasthan 333031",
        "website": "https://www.bits-pilani.ac.in",
        "nirf_rank": 20,
        "latitude": 28.3639,
        "longitude": 75.5870,
        "is_nodal_center": False,
    },
    {
        "name": "College of Engineering, Pune",
        "short_name": "COEP Tech",
        "code": "C-41523",
        "institution_type": "Unitary Public State University",
        "state": "Maharashtra",
        "district": "Pune",
        "city": "Pune",
        "address": "Wellesley Rd, Shivajinagar, Pune, Maharashtra 411005",
        "website": "https://www.coep.org.in",
        "nirf_rank": 73,
        "latitude": 18.5293,
        "longitude": 73.8565,
    },
    {
        "name": "Delhi Technological University",
        "short_name": "DTU Delhi",
        "code": "U-0099",
        "institution_type": "State University",
        "state": "Delhi",
        "district": "North West Delhi",
        "city": "Delhi",
        "address": "Shahbad Daulatpur, Main Bawana Road, Delhi 110042",
        "website": "http://dtu.ac.in",
        "nirf_rank": 29,
        "latitude": 28.7499,
        "longitude": 77.1170,
    },
    {
        "name": "Anna University, CEG Campus",
        "short_name": "CEG Anna University",
        "code": "U-0439",
        "institution_type": "State University",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "city": "Chennai",
        "address": "Sardar Patel Road, Guindy, Chennai, Tamil Nadu 600025",
        "website": "https://www.annauniv.edu",
        "nirf_rank": 13,
        "latitude": 13.0109,
        "longitude": 80.2354,
    },
    {
        "name": "Jadavpur University",
        "short_name": "Jadavpur Univ",
        "code": "U-0573",
        "institution_type": "State University",
        "state": "West Bengal",
        "district": "Kolkata",
        "city": "Kolkata",
        "address": "188, Raja S.C. Mallick Rd, Jadavpur, Kolkata, West Bengal 700032",
        "website": "http://www.jaduniv.edu.in",
        "nirf_rank": 10,
        "latitude": 22.4989,
        "longitude": 88.3718,
        "is_nodal_center": False,
    },
    {
        "name": "Jawaharlal Nehru Technological University Hyderabad",
        "short_name": "JNTU Hyderabad",
        "code": "U-0017",
        "institution_type": "State University",
        "state": "Telangana",
        "district": "Hyderabad",
        "city": "Hyderabad",
        "address": "Kukatpally, Hyderabad, Telangana 500085",
        "website": "https://jntuh.ac.in",
        "nirf_rank": 88,
        "latitude": 17.4933,
        "longitude": 78.3914,
    },
    {
        "name": "R.V. College of Engineering",
        "short_name": "RVCE Bengaluru",
        "code": "C-1296",
        "institution_type": "Autonomous Private Engineering College",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "city": "Bengaluru",
        "address": "Mysore Road, RV Vidyanikethan Post, Bengaluru, Karnataka 560059",
        "website": "https://www.rvce.edu.in",
        "nirf_rank": 96,
        "latitude": 12.9237,
        "longitude": 77.4987,
    },
    {
        "name": "PSG College of Technology",
        "short_name": "PSG Tech",
        "code": "C-41221",
        "institution_type": "Autonomous Govt-Aided College",
        "state": "Tamil Nadu",
        "district": "Coimbatore",
        "city": "Coimbatore",
        "address": "Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641004",
        "website": "https://www.psgtech.edu",
        "nirf_rank": 63,
        "latitude": 11.0244,
        "longitude": 77.0033,
        "is_nodal_center": False,
    },
    {
        "name": "Vellore Institute of Technology",
        "short_name": "VIT Vellore",
        "code": "U-0490",
        "institution_type": "Deemed to be University",
        "state": "Tamil Nadu",
        "district": "Vellore",
        "city": "Vellore",
        "address": "Katpadi, Vellore, Tamil Nadu 632014",
        "website": "https://vit.ac.in",
        "nirf_rank": 11,
        "latitude": 12.9692,
        "longitude": 79.1559,
    },
    # --- Authentic Lending Institutions & Channel Partners (SCAs, PSBs, RRBs, NBFC-MFIs) ---
    {
        "name": "State Bank of India - Chennai Main Branch",
        "short_name": "SBI Chennai Main",
        "code": "SBIN0000800",
        "institution_type": "PSB",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "city": "Chennai",
        "address": "22, Rajaji Salai, Chennai, Tamil Nadu 600001",
        "website": "https://sbi.co.in",
        "latitude": 13.0883,
        "longitude": 80.2907,
        "status": "active"
    },
    {
        "name": "Tamil Nadu Adi Dravidar Housing & Development Corp (TAHDCO) - Chennai SCA",
        "short_name": "TAHDCO Chennai",
        "code": "TAHDCO-CHN-01",
        "institution_type": "SCA",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "city": "Chennai",
        "address": "31, Cenotaph Road, Teynampet, Chennai, Tamil Nadu 600018",
        "website": "https://tahdco.tn.gov.in",
        "latitude": 13.0368,
        "longitude": 80.2458,
        "status": "active"
    },
    {
        "name": "Indian Bank - Zonal Lead Bank Office Pune",
        "short_name": "Indian Bank Pune",
        "code": "IDIB000P045",
        "institution_type": "PSB",
        "state": "Maharashtra",
        "district": "Pune",
        "city": "Pune",
        "address": "F.C. Road, Shivajinagar, Pune, Maharashtra 411004",
        "website": "https://www.indianbank.in",
        "latitude": 18.5284,
        "longitude": 73.8428,
        "status": "active"
    },
    {
        "name": "Maharashtra State Financial Corporation (MSFC) - Pune Regional Office",
        "short_name": "MSFC Pune",
        "code": "MSFC-PUN-01",
        "institution_type": "SCA",
        "state": "Maharashtra",
        "district": "Pune",
        "city": "Pune",
        "address": "Senapati Bapat Road, Shivajinagar, Pune, Maharashtra 411016",
        "website": "https://msfc.maharashtra.gov.in",
        "latitude": 18.5332,
        "longitude": 73.8306,
        "status": "active"
    },
    {
        "name": "Maharashtra Gramin Bank - Hadapsar Branch",
        "short_name": "MGB Hadapsar",
        "code": "MAHG000412",
        "institution_type": "RRB",
        "state": "Maharashtra",
        "district": "Pune",
        "city": "Pune",
        "address": "Magarpatta Road, Hadapsar, Pune, Maharashtra 411028",
        "website": "https://mahagramin.in",
        "latitude": 18.5089,
        "longitude": 73.9259,
        "status": "active"
    },
    {
        "name": "Annasaheb Patil Arthik Vikas Mahamandal (APAVM) - Pune Liaison Cell",
        "short_name": "APAVM Pune Cell",
        "code": "APAVM-PUN-DIR",
        "institution_type": "SCA",
        "state": "Maharashtra",
        "district": "Pune",
        "city": "Pune",
        "address": "Administrative Complex, Near Collector Office, Pune 411001",
        "website": "https://apavm.maharashtra.gov.in",
        "latitude": None,
        "longitude": None,
        "status": "active"
    },
    {
        "name": "Punjab National Bank - Connaught Place Large Corporate & MSME Branch",
        "short_name": "PNB Connaught Place",
        "code": "PUNB0000100",
        "institution_type": "PSB",
        "state": "Delhi",
        "district": "New Delhi",
        "city": "New Delhi",
        "address": "ECE House, 28 Kasturba Gandhi Marg, Connaught Place, New Delhi 110001",
        "website": "https://pnbindia.in",
        "latitude": 28.6289,
        "longitude": 77.2219,
        "status": "active"
    },
    {
        "name": "Delhi SC/ST/OBC/Minorities Financial & Development Corp (DSFDC)",
        "short_name": "DSFDC New Delhi",
        "code": "DSFDC-NDL-01",
        "institution_type": "SCA",
        "state": "Delhi",
        "district": "New Delhi",
        "city": "New Delhi",
        "address": "Ambedkar Bhawan, Sector 16, Rohini / Central Office, New Delhi 110002",
        "website": "https://dsfdc.delhi.gov.in",
        "latitude": 28.6448,
        "longitude": 77.2167,
        "status": "active"
    },
    {
        "name": "Karnataka Gramin Bank - Head Office & MSME Cell",
        "short_name": "KGB Bellary Road",
        "code": "PKGB0001001",
        "institution_type": "RRB",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "city": "Bengaluru",
        "address": "Gandhinagar, Bengaluru, Karnataka 560009",
        "website": "https://karnatakagraminbank.com",
        "latitude": 12.9778,
        "longitude": 77.5772,
        "status": "active"
    },
    {
        "name": "Canara Bank - Micro & Small Enterprise Hub Bengaluru",
        "short_name": "Canara MSME Hub",
        "code": "CNRB0000112",
        "institution_type": "PSB",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "city": "Bengaluru",
        "address": "112, J.C. Road, Bengaluru, Karnataka 560002",
        "website": "https://canarabank.com",
        "latitude": 12.9629,
        "longitude": 77.5855,
        "status": "active"
    },
    {
        "name": "Karnataka State Minorities Development Corp (KSMDC) - Bangalore Urban",
        "short_name": "KSMDC Bangalore",
        "code": "KSMDC-BLR-01",
        "institution_type": "SCA",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "city": "Bengaluru",
        "address": "V.V. Towers, Dr. B.R. Ambedkar Veedhi, Bengaluru 560001",
        "website": "https://ksmdc.karnataka.gov.in",
        "latitude": 12.9784,
        "longitude": 77.5921,
        "status": "active"
    },
    {
        "name": "Asmitha Microfin / NBFC Facilitation Desk - Bengaluru Regional",
        "short_name": "Asmitha Microfin",
        "code": "NBFC-BLR-09",
        "institution_type": "NBFC-MFI",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "city": "Bengaluru",
        "address": "Koramangala 4th Block, Bengaluru, Karnataka 560034",
        "website": "https://mfinindia.org",
        "latitude": 12.9345,
        "longitude": 77.6265,
        "status": "active"
    },
    {
        "name": "Bengaluru Rural District Industries Center (DIC)",
        "short_name": "DIC Bangalore Rural",
        "code": "DIC-BLR-RUR",
        "institution_type": "SCA",
        "state": "Karnataka",
        "district": "Bangalore Rural",
        "city": "Devanahalli",
        "address": "Mini Vidhana Soudha, Devanahalli, Bangalore Rural 562110",
        "website": "https://karnatakaindustry.gov.in",
        "latitude": None,
        "longitude": None,
        "status": "active"
    }
]


def seed_institutions_and_sih():
    db = SessionLocal()
    print("🌱 [Yojantra Seed] Seeding Partner Institutions and Facilitation Centers...")

    # Allowed keys for Institution model
    allowed_keys = {
        "name", "short_name", "code", "institution_type",
        "state", "district", "city", "address", "website",
        "affiliation", "nirf_rank", "latitude", "longitude", "status"
    }

    seeded_inst = 0
    for data in INSTITUTIONS_SEED_DATA:
        clean_data = {k: v for k, v in data.items() if k in allowed_keys}
        existing = db.query(Institution).filter(
            (Institution.name == clean_data["name"]) | 
            (Institution.code == clean_data.get("code"))
        ).first()

        if not existing:
            inst = Institution(id=uuid.uuid4(), **clean_data)
            db.add(inst)
            seeded_inst += 1

    db.commit()
    print(f"✓ Added {seeded_inst} partner institutions (Total now: {db.query(Institution).count()}).")
    db.close()


if __name__ == "__main__":
    seed_institutions_and_sih()
