"""initial_schema

Revision ID: 487b7be2fe28
Revises: 
Create Date: 2026-09-07 19:03:59.389450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487b7be2fe28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csc_centers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('csc_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('services_offered', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csc_centers_csc_id'), 'csc_centers', ['csc_id'], unique=True)
    op.create_index(op.f('ix_csc_centers_district'), 'csc_centers', ['district'], unique=False)
    op.create_index(op.f('ix_csc_centers_state'), 'csc_centers', ['state'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_phone'), 'otp_verifications', ['phone'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ministry', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheme_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('max_benefit_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_benefit_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('benefit_description', sa.Text(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subsidy_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_loan_amount_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('collateral_required', sa.Boolean(), nullable=True),
    sa.Column('application_mode', sa.String(length=20), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('helpline_number', sa.String(length=50), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('is_national', sa.Boolean(), nullable=True),
    sa.Column('applicable_states', sa.JSON(), nullable=True),
    sa.Column('target_genders', sa.JSON(), nullable=True),
    sa.Column('target_social_categories', sa.JSON(), nullable=True),
    sa.Column('target_business_types', sa.JSON(), nullable=True),
    sa.Column('target_business_stages', sa.JSON(), nullable=True),
    sa.Column('min_turnover_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_turnover_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_employees', sa.Integer(), nullable=True),
    sa.Column('max_employees', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('women_ownership_min_percent', sa.Integer(), nullable=True),
    sa.Column('requires_udyam', sa.Boolean(), nullable=True),
    sa.Column('requires_gst', sa.Boolean(), nullable=True),
    sa.Column('requires_dpiit', sa.Boolean(), nullable=True),
    sa.Column('documents_required', sa.JSON(), nullable=True),
    sa.Column('application_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_ministry'), 'schemes', ['ministry'], unique=False)
    op.create_index(op.f('ix_schemes_name'), 'schemes', ['name'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_type'), 'schemes', ['scheme_type'], unique=False)
    op.create_index(op.f('ix_schemes_status'), 'schemes', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('social_category', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('block_tehsil', sa.String(length=100), nullable=True),
    sa.Column('village_ward', sa.String(length=100), nullable=True),
    sa.Column('is_rural', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('literacy_level', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=True),
    sa.Column('udyam_number', sa.String(length=50), nullable=True),
    sa.Column('dpiit_number', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('fssai_license', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_deadline', sa.Date(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('documents_uploaded', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('business_stage', sa.String(length=50), nullable=True),
    sa.Column('annual_turnover_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('num_women_employees', sa.Integer(), nullable=True),
    sa.Column('years_in_operation', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_women_led', sa.Boolean(), nullable=True),
    sa.Column('is_sc_st_led', sa.Boolean(), nullable=True),
    sa.Column('registration_type', sa.String(length=100), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('has_collateral', sa.Boolean(), nullable=True),
    sa.Column('funding_needed_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('funding_purpose', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('intent_detected', sa.String(length=50), nullable=True),
    sa.Column('schemes_discussed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_number_hash', sa.String(length=64), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('rule_value', sa.JSON(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rules_scheme_id'), 'eligibility_rules', ['scheme_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('scheme_benefits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('benefit_type', sa.String(length=50), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disbursement_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_benefits_scheme_id'), 'scheme_benefits', ['scheme_id'], unique=False)
    op.create_table('scheme_bookmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_bookmarks_scheme_id'), 'scheme_bookmarks', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_bookmarks_user_id'), 'scheme_bookmarks', ['user_id'], unique=False)
    op.create_table('user_scheme_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('eligibility_status', sa.String(length=50), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scheme_matches_is_applied'), 'user_scheme_matches', ['is_applied'], unique=False)
    op.create_index(op.f('ix_user_scheme_matches_is_bookmarked'), 'user_scheme_matches', ['is_bookmarked'], unique=False)
    op.create_index(op.f('ix_user_scheme_matches_is_recommended'), 'user_scheme_matches', ['is_recommended'], unique=False)
    op.create_index(op.f('ix_user_scheme_matches_scheme_id'), 'user_scheme_matches', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_user_scheme_matches_user_id'), 'user_scheme_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scheme_matches_user_id'), table_name='user_scheme_matches')
    op.drop_index(op.f('ix_user_scheme_matches_scheme_id'), table_name='user_scheme_matches')
    op.drop_index(op.f('ix_user_scheme_matches_is_recommended'), table_name='user_scheme_matches')
    op.drop_index(op.f('ix_user_scheme_matches_is_bookmarked'), table_name='user_scheme_matches')
    op.drop_index(op.f('ix_user_scheme_matches_is_applied'), table_name='user_scheme_matches')
    op.drop_table('user_scheme_matches')
    op.drop_index(op.f('ix_scheme_bookmarks_user_id'), table_name='scheme_bookmarks')
    op.drop_index(op.f('ix_scheme_bookmarks_scheme_id'), table_name='scheme_bookmarks')
    op.drop_table('scheme_bookmarks')
    op.drop_index(op.f('ix_scheme_benefits_scheme_id'), table_name='scheme_benefits')
    op.drop_table('scheme_benefits')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_eligibility_rules_scheme_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schemes_status'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_type'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_name'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_ministry'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_otp_verifications_phone'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_csc_centers_state'), table_name='csc_centers')
    op.drop_index(op.f('ix_csc_centers_district'), table_name='csc_centers')
    op.drop_index(op.f('ix_csc_centers_csc_id'), table_name='csc_centers')
    op.drop_table('csc_centers')
    # ### end Alembic commands ###
